#ifndef KEYMAP_H__
#define KEYMAP_H__
#include <string.h>
#include "libretro.h"
//#include <shared/enum_decl.h>
//#include "../beeb/include/beeb/keys.inl"
//#include <shared/enum_end.h>
const std::map<unsigned, BeebKey> beeb_libretro_keymap = {
    {RETROK_SPACE,    BeebKey_Space},
    {RETROK_COMMA,    BeebKey_Comma},
    {RETROK_MINUS,    BeebKey_Minus},
    {RETROK_PERIOD,   BeebKey_Stop},
    {RETROK_SLASH,    BeebKey_Slash},
    {RETROK_0,        BeebKey_0},
    {RETROK_1,        BeebKey_1},
    {RETROK_2,        BeebKey_2},
    {RETROK_3,        BeebKey_3},
    {RETROK_4,        BeebKey_4},
    {RETROK_5,        BeebKey_5},
    {RETROK_6,        BeebKey_6},
    {RETROK_7,        BeebKey_7},
    {RETROK_8,        BeebKey_8},
    {RETROK_9,        BeebKey_9},
    {RETROK_QUOTE,    BeebKey_Colon},
    {RETROK_SEMICOLON,BeebKey_Semicolon},
    {RETROK_HOME,     BeebKey_Backslash},
    {RETROK_a,        BeebKey_A},
    {RETROK_b,        BeebKey_B},
    {RETROK_c,        BeebKey_C},
    {RETROK_d,        BeebKey_D},
    {RETROK_e,        BeebKey_E},
    {RETROK_f,        BeebKey_F},
    {RETROK_g,        BeebKey_G},
    {RETROK_h,        BeebKey_H},
    {RETROK_i,        BeebKey_I},
    {RETROK_j,        BeebKey_J},
    {RETROK_k,        BeebKey_K},
    {RETROK_l,        BeebKey_L},
    {RETROK_m,        BeebKey_M},
    {RETROK_n,        BeebKey_N},
    {RETROK_o,        BeebKey_O},
    {RETROK_p,        BeebKey_P},
    {RETROK_q,        BeebKey_Q},
    {RETROK_r,        BeebKey_R},
    {RETROK_s,        BeebKey_S},
    {RETROK_t,        BeebKey_T},
    {RETROK_u,        BeebKey_U},
    {RETROK_v,        BeebKey_V},
    {RETROK_w,        BeebKey_W},
    {RETROK_x,        BeebKey_X},
    {RETROK_y,        BeebKey_Y},
    {RETROK_z,        BeebKey_Z},
    {RETROK_RIGHTBRACKET,BeebKey_LeftSquareBracket},
    {RETROK_LEFTBRACKET,BeebKey_At},
    {RETROK_BACKSLASH,BeebKey_RightSquareBracket},
    {RETROK_EQUALS,   BeebKey_Caret},
    {RETROK_OEM_102,  BeebKey_Underline},
    {RETROK_ESCAPE,   BeebKey_Escape},
    {RETROK_TAB,      BeebKey_Tab},
    {RETROK_RCTRL,    BeebKey_Ctrl},
    {RETROK_PAGEUP,   BeebKey_CapsLock},
    {RETROK_NUMLOCK,  BeebKey_ShiftLock},
    {RETROK_LSHIFT,   BeebKey_Shift},
    {RETROK_RSHIFT,   BeebKey_Shift},
    {RETROK_BACKSPACE,BeebKey_Delete},
    {RETROK_END,      BeebKey_Copy},
    {RETROK_RETURN,   BeebKey_Return},
    {RETROK_UP,       BeebKey_Up},
    {RETROK_DOWN,     BeebKey_Down},
    {RETROK_LEFT,     BeebKey_Left},
    {RETROK_RIGHT,    BeebKey_Right},
    {RETROK_F10,      BeebKey_f0},
    {RETROK_F1,       BeebKey_f1},
    {RETROK_F2,       BeebKey_f2},
    {RETROK_F3,       BeebKey_f3},
    {RETROK_F4,       BeebKey_f4},
    {RETROK_F5,       BeebKey_f5},
    {RETROK_F6,       BeebKey_f6},
    {RETROK_F7,       BeebKey_f7},
    {RETROK_F8,       BeebKey_f8},
    {RETROK_F9,       BeebKey_f9},
    {RETROK_F11,      BeebKey_Break},
    {RETROK_KP0,      BeebKey_Keypad0},
    {RETROK_KP1,      BeebKey_Keypad1},
    {RETROK_KP2,      BeebKey_Keypad2},
    {RETROK_KP3,      BeebKey_Keypad3},
    {RETROK_KP4,      BeebKey_Keypad4},
    {RETROK_KP5,      BeebKey_Keypad5},
    {RETROK_KP6,      BeebKey_Keypad6},
    {RETROK_KP7,      BeebKey_Keypad7},
    {RETROK_KP8,      BeebKey_Keypad8},
    {RETROK_KP9,      BeebKey_Keypad9},
    {RETROK_KP_PERIOD,BeebKey_KeypadStop},
    {RETROK_KP_ENTER, BeebKey_KeypadReturn},
    {RETROK_KP_PLUS,  BeebKey_KeypadPlus},
    {RETROK_KP_MINUS, BeebKey_KeypadMinus},
    {RETROK_KP_DIVIDE,BeebKey_KeypadSlash},
    {RETROK_KP_MULTIPLY,BeebKey_KeypadStar},
};


#endif

