#define ENAME BeebLinkState
EBEGIN()
EPN(BeebToServerType)
EPN(BeebToServerSize0)
EPN(BeebToServerSize1)
EPN(BeebToServerSize2)
EPN(BeebToServerSize3)
EPN(BeebToServerPayload)
EPN(ServerToBeebSize0)
EPN(ServerToBeebSize1)
EPN(ServerToBeebSize2)
EPN(ServerToBeebSize3)
EPN(ServerToBeebPayload)
EEND()
#undef ENAME
