BEEB_EVENT_TYPE(None)
BEEB_EVENT_TYPE(KeyState)
BEEB_EVENT_TYPE(LoadDiscImage)
BEEB_EVENT_TYPE(ChangeConfig)
BEEB_EVENT_TYPE(HardReset)
BEEB_EVENT_TYPE(SetTurboDisc)
BEEB_EVENT_TYPE(SaveState)
BEEB_EVENT_TYPE(LoadState)
BEEB_EVENT_TYPE(WindowProxy)
BEEB_EVENT_TYPE(Root)
BEEB_EVENT_TYPE(StartPaste)
BEEB_EVENT_TYPE(StopPaste)
#if BBCMICRO_DEBUGGER
BEEB_EVENT_TYPE(SetByte)
#endif
#undef BEEB_EVENT_TYPE
