#define ENAME int
NBEGIN(CVReturn)
NN(kCVReturnSuccess)
//NN(kCVReturnFirst)
NN(kCVReturnError)
NN(kCVReturnInvalidArgument)
NN(kCVReturnAllocationFailed)
NN(kCVReturnUnsupported)
NN(kCVReturnInvalidDisplay)
NN(kCVReturnDisplayLinkAlreadyRunning)
NN(kCVReturnDisplayLinkNotRunning)
NN(kCVReturnDisplayLinkCallbacksNotSet)
NN(kCVReturnInvalidPixelFormat)
NN(kCVReturnInvalidSize)
NN(kCVReturnInvalidPixelBufferAttributes)
NN(kCVReturnPixelBufferNotOpenGLCompatible)
NN(kCVReturnPixelBufferNotMetalCompatible)
NN(kCVReturnWouldExceedAllocationThreshold)
NN(kCVReturnPoolAllocationFailed)
NN(kCVReturnInvalidPoolAttributes)
NN(kCVReturnRetry)
//NN(kCVReturnLast)
NEND()
#undef ENAME

#define ENAME NSInteger
NBEGIN(AVAssetWriterStatus)
NN(AVAssetWriterStatusUnknown)
NN(AVAssetWriterStatusWriting)
NN(AVAssetWriterStatusCompleted)
NN(AVAssetWriterStatusFailed)
NN(AVAssetWriterStatusCancelled)
NEND()
#undef ENAME
