name: Build b2

on:
  push:
    branches:
      - master
      - wip/master
      - wip/ci_test

jobs:
  build-linux-x64-gcc-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci-ubuntu-gcc-ffmpeg UPLOAD=1
        env:
          GH_TOKEN: ${{ github.token }}
        
  build-linux-x64-clang-ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci-ubuntu-clang-ffmpeg

  build-linux-arm-gcc-ffmpeg:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci-ubuntu-gcc-ffmpeg
        env:
          GH_TOKEN: ${{ github.token }}
        
  build-linux-arm-clang-ffmpeg:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci-ubuntu-clang-ffmpeg

  build-linux-x64-gcc-no_ffmpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci-ubuntu-gcc-no_ffmpeg

  build-windows-x64:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_windows UPLOAD=1
        env:
          GH_TOKEN: ${{ github.token }}

  build-windows-arm:
    runs-on: 11-arm
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_windows
        env:
          GH_TOKEN: ${{ github.token }}

  build-macos-x64:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_macos_homebrew
      - run: make github_ci_macos_homebrew_ffmpeg
      - run: make github_ci_macos_x64
        env:
          GH_TOKEN: ${{ github.token }}
          
  build-older-macos-x64:
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_macos_homebrew
      - run: make github_ci_older_macos_x64
        env:
          GH_TOKEN: ${{ github.token }}
          
  build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: make github_ci_macos_homebrew
      - run: make github_ci_macos_homebrew_ffmpeg
      - run: make github_ci_macos_arm
        env:
          GH_TOKEN: ${{ github.token }}
